### PR TITLE
feat: show browser not supported popup at startup

### PR DESCRIPTION
**Pull request by pajotg**
This PR adds a popup at startup when you are using a browser that doesn't support web-serial like firefox
image

### CODE REVIEW

**Review by sverben — CHANGES_REQUESTED** [review]
Please first detect if we can use a fallback driver

**Review by sverben — CHANGES_REQUESTED** [review]
Please copy the styling from the warning dialog, also differentiate between the recommended (primary) and secondary buttons with styling, in this case primary would probably be "I understand", and secondary "don't show again"

**Comment by pajotg** [comment]
This is what it looks like now.
image

> Please first detect if we can use a fallback driver
Im hoping detecting if navigator.usb is what you meant with this, or would it need to attempt to connect?

**Comment by rmoesbergen** [comment]
> 
> > Please first detect if we can use a fallback driver
> 
> Im hoping detecting if navigator.usb is what you meant with this, or would it need to attempt to connect?

The check is not correct this way, since firefox does support WebUSB, but we only support uploads to FTDI devices with WebUSB. So if you try to upload to a CH340 based device using firefox, you would not get the dialog, but the upload would fail. I don't think we can reliably check for this at startup, since you have to know which device is connected. I guess the check needs to move to after where the connection is made.

**Review by koen1711 — APPROVED** [review]

**Review by rmoesbergen — APPROVED** [review]

**Pull request merged**
